FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat openssl curl

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate

EXPOSE 5555

CMD ["npx", "prisma", "studio", "--port", "5555", "--hostname", "0.0.0.0"]