FROM node:22-alpine

WORKDIR /app

RUN apk add --no-cache openssl libc6-compat

COPY package*.json ./

RUN npm ci

COPY . .

RUN npx prisma generate

CMD ["npx", "prisma", "migrate", "deploy", "--schema=./prisma/schema.prisma"]